# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datavengers_2020.models.base_model_ import Model
from datavengers_2020 import util


class AlgorithmType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    RF = "RF"
    Q_LEARNER = "Q-learner"
    def __init__(self):  # noqa: E501
        """AlgorithmType - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'AlgorithmType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AlgorithmType of this AlgorithmType.  # noqa: E501
        :rtype: AlgorithmType
        """
        return util.deserialize_model(dikt, cls)
