# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from datavengers_2020.models.base_model_ import Model
from datavengers_2020 import util


class StockPrice(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _date: datetime=None, open: float=None, high: float=None, low: float=None, close: float=None, adj_close: float=None, volume: float=None):  # noqa: E501
        """StockPrice - a model defined in Swagger

        :param _date: The _date of this StockPrice.  # noqa: E501
        :type _date: datetime
        :param open: The open of this StockPrice.  # noqa: E501
        :type open: float
        :param high: The high of this StockPrice.  # noqa: E501
        :type high: float
        :param low: The low of this StockPrice.  # noqa: E501
        :type low: float
        :param close: The close of this StockPrice.  # noqa: E501
        :type close: float
        :param adj_close: The adj_close of this StockPrice.  # noqa: E501
        :type adj_close: float
        :param volume: The volume of this StockPrice.  # noqa: E501
        :type volume: float
        """
        self.swagger_types = {
            '_date': datetime,
            'open': float,
            'high': float,
            'low': float,
            'close': float,
            'adj_close': float,
            'volume': float
        }

        self.attribute_map = {
            '_date': 'date',
            'open': 'open',
            'high': 'high',
            'low': 'low',
            'close': 'close',
            'adj_close': 'adj_close',
            'volume': 'volume'
        }
        self.__date = _date
        self._open = open
        self._high = high
        self._low = low
        self._close = close
        self._adj_close = adj_close
        self._volume = volume

    @classmethod
    def from_dict(cls, dikt) -> 'StockPrice':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The StockPrice of this StockPrice.  # noqa: E501
        :rtype: StockPrice
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _date(self) -> datetime:
        """Gets the _date of this StockPrice.


        :return: The _date of this StockPrice.
        :rtype: datetime
        """
        return self.__date

    @_date.setter
    def _date(self, _date: datetime):
        """Sets the _date of this StockPrice.


        :param _date: The _date of this StockPrice.
        :type _date: datetime
        """
        if _date is None:
            raise ValueError("Invalid value for `_date`, must not be `None`")  # noqa: E501

        self.__date = _date

    @property
    def open(self) -> float:
        """Gets the open of this StockPrice.


        :return: The open of this StockPrice.
        :rtype: float
        """
        return self._open

    @open.setter
    def open(self, open: float):
        """Sets the open of this StockPrice.


        :param open: The open of this StockPrice.
        :type open: float
        """
        if open is None:
            raise ValueError("Invalid value for `open`, must not be `None`")  # noqa: E501

        self._open = open

    @property
    def high(self) -> float:
        """Gets the high of this StockPrice.


        :return: The high of this StockPrice.
        :rtype: float
        """
        return self._high

    @high.setter
    def high(self, high: float):
        """Sets the high of this StockPrice.


        :param high: The high of this StockPrice.
        :type high: float
        """
        if high is None:
            raise ValueError("Invalid value for `high`, must not be `None`")  # noqa: E501

        self._high = high

    @property
    def low(self) -> float:
        """Gets the low of this StockPrice.


        :return: The low of this StockPrice.
        :rtype: float
        """
        return self._low

    @low.setter
    def low(self, low: float):
        """Sets the low of this StockPrice.


        :param low: The low of this StockPrice.
        :type low: float
        """
        if low is None:
            raise ValueError("Invalid value for `low`, must not be `None`")  # noqa: E501

        self._low = low

    @property
    def close(self) -> float:
        """Gets the close of this StockPrice.


        :return: The close of this StockPrice.
        :rtype: float
        """
        return self._close

    @close.setter
    def close(self, close: float):
        """Sets the close of this StockPrice.


        :param close: The close of this StockPrice.
        :type close: float
        """
        if close is None:
            raise ValueError("Invalid value for `close`, must not be `None`")  # noqa: E501

        self._close = close

    @property
    def adj_close(self) -> float:
        """Gets the adj_close of this StockPrice.


        :return: The adj_close of this StockPrice.
        :rtype: float
        """
        return self._adj_close

    @adj_close.setter
    def adj_close(self, adj_close: float):
        """Sets the adj_close of this StockPrice.


        :param adj_close: The adj_close of this StockPrice.
        :type adj_close: float
        """
        if adj_close is None:
            raise ValueError("Invalid value for `adj_close`, must not be `None`")  # noqa: E501

        self._adj_close = adj_close

    @property
    def volume(self) -> float:
        """Gets the volume of this StockPrice.


        :return: The volume of this StockPrice.
        :rtype: float
        """
        return self._volume

    @volume.setter
    def volume(self, volume: float):
        """Sets the volume of this StockPrice.


        :param volume: The volume of this StockPrice.
        :type volume: float
        """
        if volume is None:
            raise ValueError("Invalid value for `volume`, must not be `None`")  # noqa: E501

        self._volume = volume
